hw03-application:
  # russian для русского
  # english для английского
  language: "english"

  filePath: "data/quiz_%s.csv"

hw03:
  # russian для русского
  # english для английского
  language: "russian"

  questionsCount: 5

application:
  name: "HW03 Spring Boot Application"