DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS(
  AUTHOR_ID BIGINT PRIMARY KEY,
  AUTHOR_SURNAME VARCHAR(100),
  AUTHOR_NAME VARCHAR(100),
  AUTHOR_PATRONYMIC VARCHAR(100)
);

DROP TABLE IF EXISTS GENRES;
CREATE TABLE GENRES(
  GENRE_ID BIGINT PRIMARY KEY,
  GENRE_NAME VARCHAR(100)
);

DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS (
  BOOK_ID BIGINT PRIMARY KEY,
  TITLE VARCHAR(100)
);

DROP TABLE IF EXISTS BOOK_R_AUTHOR;
CREATE TABLE BOOK_R_AUTHOR (
  BOOK_ID BIGINT NOT NULL,
  AUTHOR_ID BIGINT NOT NULL,
  PRIMARY KEY (BOOK_ID, AUTHOR_ID),
  FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(BOOK_ID),
  FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS(AUTHOR_ID)
);

DROP TABLE IF EXISTS BOOK_R_GENRE;
CREATE TABLE BOOK_R_GENRE (
  BOOK_ID BIGINT NOT NULL,
  GENRE_ID BIGINT NOT NULL,
  PRIMARY KEY (BOOK_ID, GENRE_ID),
  FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(BOOK_ID),
  FOREIGN KEY (GENRE_ID) REFERENCES GENRES(GENRE_ID)
);
