DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS(
  AUTHOR_ID INT PRIMARY KEY,
  AUTHOR_SURNAME VARCHAR(100),
  AUTHOR_NAME VARCHAR(100),
  AUTHOR_PATRONYMIC VARCHAR(100)
);

DROP TABLE IF EXISTS GENRES;
CREATE TABLE GENRES(
  GENRE_ID INT PRIMARY KEY,
  GENRE_NAME VARCHAR(100)
);
